{% set name = "openapi-core" %}
{% set version = "0.14.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd12cacba0d4645161e1b05165c24eb6d2962ef7962951b9603c9aa0113b2c70

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - attrs
    - isodate
    - dictpath
    - lazy-object-proxy
    - more-itertools
    - openapi-schema-validator
    - openapi-spec-validator
    - parse
    - python >=3.5
    - six
    - werkzeug

test:
  imports:
    - openapi_core
    - openapi_core.casting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p1c2u/openapi-core
  summary: client-side and server-side support for the OpenAPI Specification v3
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
